### PR TITLE
4 was for point corrs, affine need 8

### PR DESCRIPTION
**Pull request by ducha-aiki**

### CODE REVIEW

**Comment by danini** [comment]
I suggest building the neighborhood graph only on the point coordinates using . Have you tried that? 
Like this:
neighborhood::GridNeighborhoodGraph<4> neighborhoodGraph(&points(cv::Rect(0, 0, 2, pointNumber)).

Anyways, the commit is buggy: you increase the dimension but do not provided cell sizes in the added dimensions, i.e., 
the second parameter of the neighborhood::GridNeighborhoodGraph<8> constructor still contains only 4 sizes instead of the new 8. To make it work the following things has to be done:
- The grid structure currently does not work with negative values, so an offset should be added to the affine parameters ONLY when building the graph.
- Provide the bounding box sizes along the new dimensions in the constructor.

**Comment by ducha-aiki** [comment]
The line you proposed, does not work :(

Regarding having 4 - it was crashing with vlfeat error:

>The data dimension (8) does not match with the expected dimension (4).

Regarding my 4->8, isn't it is adding the 4 dimensions (affine) , at contruction, but actually ignoring them at runtime?

**Comment by ducha-aiki** [comment]
How about 

```C++
	neighborhood::GridNeighborhoodGraph<8> neighborhoodGraph(&points,
		{sourceImageWidth_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
		sourceImageHeight_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
		destinationImageWidth_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
		destinationImageHeight_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
		0.5, 0.5, 0.5, 0.5
	}
	
```	

The cell size 0.5 for the affine parameters, given than we have 8 cells, would be quite big to incorporate different things, but small enough to take "roughly similar AC"into account.

**Comment by danini** [comment]
> The line you proposed, does not work :(
> 
> Regarding having 4 - it was crashing with vlfeat error:
> 
> > The data dimension (8) does not match with the expected dimension (4).
> 
> Regarding my 4->8, isn't it is adding the 4 dimensions (affine) , at contruction, but actually ignoring them at runtime?

This line will kill you:
https://github.com/danini/graph-cut-ransac/blob/1099c6c1f54e6ea782e9a4533df4df4ba23aea16/src/pygcransac/include/neighborhood/grid_neighborhood_graph.h#L199
if the size vector is not large enough. 

The thing which I always do is what I said. Build the neighborhood graph on the point coordinates with
neighborhood::GridNeighborhoodGraph<4> neighborhoodGraph(&points(cv::Rect(0, 0, 2, pointNumber)), ...
Since it only stores point indices this will work well even if your points have more dimensions.

**Comment by danini** [comment]
> How about
> 
> ```c++
> 	neighborhood::GridNeighborhoodGraph<8> neighborhoodGraph(&points,
> 		{sourceImageWidth_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
> 		sourceImageHeight_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
> 		destinationImageWidth_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
> 		destinationImageHeight_ / static_cast<double>(kCellNumberInNeighborhoodGraph),
> 		0.5, 0.5, 0.5, 0.5
> 	}
> 	
> ```
> 
> The cell size 0.5 for the affine parameters, given than we have 8 cells, would be quite big to incorporate different things, but small enough to take "roughly similar AC"into account.

The problem:
- Still, there are negative coordinates that lead to a run-time error or will use some memory junk due to trying to assign negative numbers to indices of type size_t.
- If there are numbers larger than 0.5, that will again lead to run-time error :)

**Comment by ducha-aiki** [comment]
Are you sure that the line you are giving me, is _exactly_ the line, which works? :)

```
/Users/oldufo/dev/affine-correspondences-for-camera-geometry/src/pyrobustac/src/robustac_python.cpp:452:60: error: taking the address of a temporary object of type 'cv::Mat' [-Waddress-of-temporary]
                neighborhood::GridNeighborhoodGraph<4> neighborhoodGraph(&points(cv::Rect(0, 0, 2, pointNumber)),
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/oldufo/dev/affine-correspondences-for-camera-geometry/src/pyrobustac/src/robustac_python.cpp:452:42: error: no matching constructor for initialization of 'neighborhood::GridNeighborhoodGraph<4>'
                neighborhood::GridNeighborhoodGraph<4> neighborhoodGraph(&points(cv::Rect(0, 0, 2, pointNumber)),
                                                       ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by danini** [comment]
Ah, I did not say that! I just wanted to provide some intuition. :D 
If you wait 5 minutes, I will give you the line you are looking for.

**Comment by ducha-aiki** [comment]
I had such a thought, but failed to grasp how one could get the the cell size from the cv::Rect. Do you mean that I can get the maximum over the dimension minus minimum of the dimension and use it?

**Comment by ducha-aiki** [comment]
Ah, now I get it - you mean to construct the neighborhood using only the points, not the affinities. OK, will do that.

**Comment by danini** [comment]
Exactly! 
I made two mistakes as I see: 
- It should be "points(cv::Rect(0, 0, 4, pointNumber)" and not "points(cv::Rect(0, 0, 2, pointNumber)"
- I remember it worked earlier but probably there were some changes, so you can't poss &points(cv::Rect(0, 0, 4, pointNumber) to the function. So the easiest and ugliest is to simply create a new matrix with the same points but only containing the coordinates. I will add to my TODO list to make it work if the actual point dimension is bigger than the provided dimension number in the template.

**Comment by danini** [comment]
It can be actually interesting to find out if considering neighborhood on ACs helps. I have never done that.

**Comment by ducha-aiki** [comment]
This version seems to work

**Comment by ducha-aiki** [comment]
Are you going to merge it? :)

**Pull request merged**
